version: "3.5"

services:
  api:
    container_name: openanimeapi_api
    stdin_open: true
    build:
      dockerfile: ./docker/dev/Dockerfile
    depends_on:
      - db
      - testing_db
      - pgadmin
    volumes:
      - ./api:/app
      - /app/node_modules
  db:
    container_name: openanimeapi_db
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  testing_db:
    container_name: openanimeapi_testing_db
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5678:5432
    volumes:
      - ./postgres_testing_data:/var/lib/postgresql/data
  pgadmin:
    container_name: openanime_pgadmin
    image: dpage/pgadmin4:8.4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin/data
