name: ESLint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Nodejs
          uses: actions/setup-node@v1
          with:
            node-version: "20.11.0" 

        - name: Install Bun"
          run: npm install -g bun

        - name: Install dependencies
          run: bun install
          working-directory: ./api

        - name: Run ESLint
          run: bun lint
          working-directory: ./api